### ISSUE TITLE
Question: How to write part of image to another image?

### ISSUE THREAD

**Issue by Gigas002** [kleisauke/net-vips#25]
Hello. I have the following code on c#, using `System.Drawing` and `System.Drawing.Imaging` namespaces:

```c#
//read the input image
Image inputImage = Image.FromFile(inputFileName);
```

Then in foreach loop I crop that image to tiles:

```c#
//inside foreach
using (Bitmap outputImage = new Bitmap(TileSize, TileSize))
{
   using (Graphics graphics = Graphics.FromImage(outputImage))
   {
      graphics.DrawImage(inputImage,
                         new Rectangle(writeXPos,
                                       writeYPos,
                                       wirteXSize,
                                       writeYSize),
                         new Rectangle(readXPos,
                                       readYPos,
                                       readXSize,
                                       readYSize),
                         GraphicsUnit.Pixel);
   }

   outputImage.Save(outputFileName, ImageFormat.Png);
}
```

That works fine with little images, but when I'm trying to work with huge tiffs (like 4gb size and 20.000 x 20.000 pixel resolution bigtiff for example) the `inputImage` can not be initialized. So I tried **NetVips** in this purpose. It seems to read and write fast and successful:

```c#
using (Image inputImage = Image.Tiffload(inputFileName))
{
   using (Image outputImage = inputImage.Crop(readXPos, readYPos, readXSize, readYSize))
   {
      outputImage.Pngsave(outputFileName);
   }
}
```

But how to write that cropped part of `inputImage` to exact point and size in another image (in coordinates `writeXPos` and `writeYPos` and size of `writeXSize` and `writeYSize`. `writeXSize` and `writeYSize` are not equal to `readXSize` and `readYSize` - the input image is automatically resized to new sizes, and if not full image is filled (image resolution is `TileSize` x `TileSize`) then the other parts of image are transparent)?
Thanks in advance for your reply.

UPD

Found out about ```Embed``` method. I'll update issue after I test it.

**Comment by Gigas002** [comment]
Ok, so I tried up the following code:


```c#
Image inputImage = Image.Tiffload(inputFileName))

//inside foreach loop:

Image image = inputImage.ExtractArea(readXPos, readYPos, readXSize, readYSize);
image = image.Embed(writeXPos, writeYPos, tileSize, tileSize);
image.Pngsave(outputFileName);
image.Dispose();

```
Yet the results are different, compared to the first example:

![103767](https://user-images.githubusercontent.com/24297712/50978103-c0c99680-1504-11e9-8dfe-029531107a9b.png)
![103767](https://user-images.githubusercontent.com/24297712/50978127-d343d000-1504-11e9-9d7b-7038092f54c0.png)

First image is done by NetVips as I described above. You can see both of them are 256x256 (my `tileSize`), but the second one has transparent background and fills tile as it should.

I also tried resizing the image before embedding it:

```c#
image.ThumbnailImage(writeXSize, metadata(writeYSize); 
```

The resulting image looks better, then without it:

![103767_2](https://user-images.githubusercontent.com/24297712/50979079-cf18b200-1506-11e9-9809-8119a5d61f1f.png)

But the pixels are shifting for a bit and it takes much more time (`System.Drawing.Imaging Image` example takes ~ 17 seconds average; wtihout resizing ~ 25 seconds average; with resizing ~ 50 seconds average).

**Comment by kleisauke** [comment]
You could try this:
```csharp
var inputImage = Image.NewFromFile("huge.tif", access: Enums.Access.Sequential);

// Make a transparent image
var pixel = Image.Black(1, 1) + new double[] {0, 0, 0, 0};
var outputImage = pixel.Embed(0, 0, tileWidth, tileHeight, extend: Enums.Extend.Copy);

// Inside loop

// Scaling calculations
const double xFactor = (double) readWidth / writeWidth;
const double yFactor = (double) readHeight / writeHeight;

// Crop
var tile = inputImage.Crop(readXPos, readYPos, readWidth, readHeight);

// Resize
tile = tile.Resize(1.0 / xFactor, vscale: 1.0 / yFactor, kernel: Enums.Kernel.Lanczos3);

// Add alpha channel
tile = tile.Bandjoin(255);

// Insert tile into output image
outputImage = outputImage.Insert(tile, writeXPos, writeYPos);

// End loop

outputImage.WriteToFile("test.png");
```

(my apologies for the slow reply)

**Comment by Gigas002** [comment]
Thanks for detailed reply. I tried out this version. The performance is still not very good (~1 min 10 sec per run, but I'm glad it can handle huge tiffs) and I had to change some details (I used Random access for inputImage, because when I tried to crop 11Gb Tiff it was completely loaded to the memory). 

It really produces nice transparent tiles, but there's still a little pixel shift on output image, which is very important when I join these tiles with each others. Here you can see it by comparing images (1 is good, 2 with shift). I also tried different `Enums.Kernel` options, but the shift remained.

![3](https://user-images.githubusercontent.com/24297712/51063023-294e6b80-160a-11e9-8d91-e3b4be222ce3.png)
![2](https://user-images.githubusercontent.com/24297712/51063024-2b182f00-160a-11e9-9696-53d83c4c9384.png)

**Comment by kleisauke** [comment]
The shift you see is due to the corner vs. centre convention on downsize (I think). 

`vips_resize` uses centre convention on downsizing. If you want use corner sampling, you'll need to write some more code (since there's no way to prefer corner over centre convention in `vips_resize`), see:

<details>
 <summary>Code details</summary>

```csharp
var inputImage = Image.NewFromFile("huge.tif", access: Enums.Access.Sequential);

// Make a transparent image
var outputImage = Image.Black(tileWidth, tileHeight).NewFromImage(new[] {0, 0, 0, 0});

// Use corner sampling rather than centre convention.
const bool centre = false;

// Inside loop

// Crop
var tile = inputImage.Crop(readXPos, readYPos, readWidth, readHeight);

// Resize
// Scaling calculations
var xFactor = (double)readWidth / writeWidth;
var yFactor = (double)readHeight / writeHeight;

// Calculate integral box shrink
var xShrink = Math.Max(1, (int) Math.Floor(xFactor));
var yShrink = Math.Max(1, (int) Math.Floor(yFactor));

// Calculate residual float affine transformation
var xResidual = xShrink / xFactor;
var yResidual = yShrink / yFactor;

// Fast, integral box-shrink
if (xShrink > 1 || yShrink > 1)
{
    if (xShrink > 1)
    {
        Console.WriteLine("shrinkv by " + yShrink);
        tile = tile.Shrinkv(yShrink);
    }
    if (yShrink > 1)
    {
        Console.WriteLine("shrinkh by " + yShrink);
        tile = tile.Shrinkh(xShrink);
    }

    // Recalculate residual float based on dimensions of required vs shrunk images
    var shrunkWidth = tile.Width;
    var shrunkHeight = tile.Height;

    xResidual = (double) writeWidth / shrunkWidth;
    yResidual = (double) writeHeight / shrunkHeight;
}

// Use affine increase or kernel reduce with the remaining float part
if (xResidual != 1.0 || yResidual != 1.0)
{
    // Perform kernel-based reduction
    if (yResidual < 1.0 || xResidual < 1.0)
    {
        if (yResidual < 1.0)
        {
            Console.WriteLine("residual reducev by " + yResidual);
            tile = tile.Reducev(1.0 / yResidual, kernel: Enums.Kernel.Lanczos3, centre: centre);
        }
        if (xResidual < 1.0)
        {
            Console.WriteLine("residual reduceh by " + xResidual);
            tile = tile.Reduceh(1.0 / xResidual, kernel: Enums.Kernel.Lanczos3, centre: centre);
        }
    }

    // Perform enlargement
    if (yResidual > 1.0 || xResidual > 1.0)
    {
        // Floating point affine transformation
        var interpolator = Interpolate.NewFromName("bicubic");
        if (yResidual > 1.0 && xResidual > 1.0)
        {
            Console.WriteLine("residual scale " + xResidual + " x " + yResidual);
            tile = tile.Affine(new []{ xResidual, 0.0, 0.0, yResidual}, interpolate: interpolator);
        }
        else if (yResidual > 1.0)
        {
            Console.WriteLine("residual scale " + yResidual);
            tile = tile.Affine(new[] { 1.0, 0.0, 0.0, yResidual }, interpolate: interpolator);
        }
        else if (xResidual > 1.0)
        {
            Console.WriteLine("residual scale " + xResidual);
            tile = tile.Affine(new[] { xResidual, 0.0, 0.0, 1.0 }, interpolate: interpolator);
        }
    }
}

// Add alpha channel
tile = tile.Bandjoin(255);

// Insert tile into output image
outputImage = outputImage.Insert(tile, writeXPos, writeYPos);

// End loop

outputImage.WriteToFile("test.png");

Console.WriteLine("Done!");
Console.ReadLine();
```
</details>
&nbsp;

I'm glad that libvips can handle huge TIFF files (I haven't tested with 11GB TIFF files). ±1 min and 10 sec per run sounds a lot, but maybe this is correct because it's such a large file. Maybe @jcupitt knows a better way to process such large files efficiently.

By the way, do you test this on Windows? If so, try testing it on Linux. It should process such large files more efficiently.

**Comment by jcupitt** [comment]
Hello @Gigas002,

What are you trying to accomplish? Perhaps there's another way.

Standard strip TIFF does not support random access, so it you want to crop random parts from an image in a loop, libvips will have to unpack the whole image to a large temporary array. You can avoid this if you use tiled tiff -- this does allow fast random access. 

You can convert your original TIFF to tiled tiff like this:

vips copy huge-strip.tif huge-tiled.tif[tile,compression=jpeg]

That turns on JPG compression as well, which might be helpful, if your images are photographic.

For benchmarking, I always find it helpful to work with complete runnable test programs. I had a go in Python -- I hope that's OK. It should be easy to convert to C#.

```python
#!/usr/bin/python3
  
import sys
import random
import pyvips

huge = pyvips.Image.new_from_file(sys.argv[1])

# make a black background image to insert our resized tiles into
background = pyvips.Image.black(10000, 10000)

tile_size = 256
scale = 0.7

for i in range(0, 100):
    # fetch source pixels from here ... tiles along the right and bottom will be
    # cropped against the image edges
    old_x = random.randint(0, huge.width)
    old_y = random.randint(0, huge.height)

    # write resized pixels here
    new_x = random.randint(0, background.width)
    new_y = random.randint(0, background.width)

    # fetch cropped tile from input ... because tiles have been cropped,
    # non-tile areas will appear transparent in the output
    tile = huge.crop(old_x, old_y,
                     min(tile_size, huge.width - tile_size),
                     min(tile_size, huge.height - tile_size))

    tile = tile.resize(scale)

    # write into background
    background = background.insert(tile, new_x, new_y)

background.write_to_file(sys.argv[2])
```

Is that roughly what you need?

I have a source image as jpg-compressed tiled tiff:

```
$ vipsheader eso1242a-pyr.tif 
eso1242a-pyr.tif: 108199x81503 uchar, 3 bands, srgb, tiffload
```

That would be 25gb uncompressed, though it's only 5gb on disc. I can run the program like this:

```
$ /usr/bin/time -f %M:%e ~/try/random-crop.py eso1242a-pyr.tif x.tif
216676:6.95
```

So it used 216 MB of ram and took 6.95 seconds.

**Comment by Gigas002** [comment]
@kleisauke

Now there’s no pixel shift, yet there’s weird black border on that place.
1 good old, 2 new with border.

![1](https://user-images.githubusercontent.com/24297712/51077681-e3051500-16ba-11e9-9fbc-95941a2c1bdf.png)
![2](https://user-images.githubusercontent.com/24297712/51077682-e4ced880-16ba-11e9-8d9c-541b3b1cd35d.png)

Currently I ran tests on Win10 x64 and Win8.1 x64. Unfortunately, I don’t have an opportunity to test this on Linux at the moment, but I’ll post results as soon as I’ll be able to do so.


Hello, @jcupitt.

That’s not exactly, what I’m trying to accomplish, but use of tiled tiffs can be a good idea.

I’m currently writing some kind of my version of  libvips’s “dzsave” (I’m targeting the same thing - create tiles), but with ability to specify min and max zooms for cropped image and to work with GeoTIFFs only. Long story short, the algorithm is working this way:

1. Get geographical coordinates, that represents image’s borders, from input image;
2. Create the `MinMax` dictionary with list of tiles (tile numbers are calculated from geographical coordinates) for each zoom, that we need to crop;
3. Then for each zoom and each tile I calculate which pixels that I should take from input image (positions and sizes) and also in which pixels will that part of the input image lie in output tile and then crop and save tile as file.

(By the way, that’s probably a good decision to crop only lowest zoom and create higher ones by joining images, but I didn’t test it yet.)

[Here’s](https://github.com/Gigas002/GTiff2Tiles/blob/master/GTiff2Tiles/GTiff2Tiles.cs) the full code, if you’re interested, will be very glad to hear some advices.

**Comment by kleisauke** [comment]
Whoops, a copy-paste mistake, I wanted to write this (I've updated my previous message):

```csharp
if (yShrink > 1)
{
    Console.WriteLine("shrinkv by " + yShrink);
    tile = tile.Shrinkv(yShrink);
}
if (xShrink > 1)
{
    Console.WriteLine("shrinkh by " + xShrink);
    tile = tile.Shrinkh(xShrink);
}
```

I'm not sure what causes the black border with corner convention resize. Perhaps this is solved by the above code.

Note for myself:
I should have another look at https://github.com/libvips/libvips/issues/703. This could be the underlying cause.

**Comment by Gigas002** [comment]
@kleisauke 
Unfortunately, that didn't solve the issue. But I also found out something interesting. I suspected it before, but I think, that these borders appears only on the lowest cropping zoom. For example, the tiles I was linking above were 17 on zoom level. Here's some 16 zoom level tiles, 1 - made by `System.Drawing.Imaging.Image`, 2 - made by `NetVips.Image` (seems like there's no difference) and the 3 one is an example of joining 4 images 17 zoom level with black borders:

![drawing](https://user-images.githubusercontent.com/24297712/51412931-4e992780-1b7e-11e9-9083-6441e61f3f7f.png)
![netvips](https://user-images.githubusercontent.com/24297712/51412983-75eff480-1b7e-11e9-84c1-0ad28806af6b.png)
![bborders](https://user-images.githubusercontent.com/24297712/51413035-95871d00-1b7e-11e9-83da-e99a6d187b24.png)

**Comment by kleisauke** [comment]
Are you able to provide a standalone code sample and test image(s) that exhibits this behavior?

**Comment by Gigas002** [comment]
> Are you able to provide a standalone code sample and test image(s) that exhibits this behavior?

Sure. Sorry it took me so long to answer.
The c# standalone class is in the [Temp.zip](https://github.com/kleisauke/net-vips/files/2825797/Temp.zip). Just create `Temp` object and run one of the `GenerateTiles` methods:

```c#
Temp temp = new temp(inputFileInfo, outputDirectoryInfo, minZ, maxZ);
temp.GenerateTilesByCropping(progress, threadsCount);
//or
temp.GenerateTilesByJoining(progress, threadsCount);
```

The `GenerateTilesByCropping` method creates tiles by cropping the input image for each zoom, the `GenerateTilesByJoining` method crops the lowest zoom and create upper tiles by joining.

That temp class will only work with the following [example](https://github.com/Gigas002/GTiff2Tiles/blob/master/Examples/Input/Input.tif) image (because I usually get coordinates and stuff from .tif using Gdal, so I couldn’t make it standalone otherwise).

I recommend you to use `minZ = 15` and `maxZ = 17` and `threadsCount = 5`. That won’t take much time for tests.

Though I'm not sure all of that will work on Linux, I tested only on Win x64.

**Comment by kleisauke** [comment]
Thanks for providing a standalone code sample and test image. I could reproduce and fix it.

Could you apply this patch?
<details>
 <summary>Temp.cs patch</summary>

```diff
diff --git a/Temp.cs b/Temp.cs
index 1111111..2222222 100644
--- a/Temp.cs
+++ b/Temp.cs
@@ -180,6 +180,8 @@ namespace Temporary
 
         private void WriteTile(int zoom, int currentX, int currentY, Image inputImage)
         {
+            const bool centreConvention = false;
+
             //Create directories for the tile. The overall structure looks like: outputDirectory/zoom/x/y.png.
             try
             {
@@ -207,8 +209,11 @@ namespace Temporary
             double yFactor = (double)readYSize / writeYSize;
 
             // Calculate integral box shrink
-            int xShrink = Math.Max(1, (int)Math.Floor(xFactor));
-            int yShrink = Math.Max(1, (int)Math.Floor(yFactor));
+            // We will get the best quality (but be the slowest) if we let reduce
+            // do all the work. Leave it the final 200 - 300% to do as a compromise
+            // for efficiency.
+            int xShrink = Math.Max(1, (int)Math.Floor(1.0 / (xFactor * 2)));
+            int yShrink = Math.Max(1, (int)Math.Floor(1.0 / (yFactor * 2)));
 
             // Calculate residual float affine transformation
             double xResidual = xShrink / xFactor;
@@ -226,42 +231,47 @@ namespace Temporary
             }
 
             // Fast, integral box-shrink
-            if (xShrink > 1 || yShrink > 1)
+            if (yShrink > 1)
             {
-                if (yShrink > 1) tile = tile.Reducev(yShrink, Enums.Kernel.Lanczos3, false);
-                if (xShrink > 1) tile = tile.Reduceh(xShrink, Enums.Kernel.Lanczos3, false);
+                tile = tile.Shrinkv(yShrink);
 
-                // Recalculate residual float based on dimensions of required vs shrunk images
-                xResidual = (double)writeXSize / tile.Width;
+                // Recalculate residual float
                 yResidual = (double)writeYSize / tile.Height;
             }
 
-            // Use affine increase or kernel reduce with the remaining float part
-            if (Math.Abs(xResidual - 1.0) > double.Epsilon ||
-                Math.Abs(yResidual - 1.0) > double.Epsilon)
+            if (xShrink > 1)
             {
-                // Perform kernel-based reduction
-                if (yResidual < 1.0 || xResidual < 1.0)
-                {
-                    if (yResidual < 1.0)
-                        tile = tile.Reducev(1.0 / yResidual, Enums.Kernel.Lanczos3, false);
-                    if (xResidual < 1.0)
-                        tile = tile.Reduceh(1.0 / xResidual, Enums.Kernel.Lanczos3, false);
-                }
+                tile = tile.Shrinkh(xShrink);
+
+                // Recalculate residual float
+                xResidual = (double)writeXSize / tile.Width;
+            }
+
+            // Perform kernel-based reduction
+            if (yResidual < 1.0)
+                tile = tile.Reducev(1.0 / yResidual, Enums.Kernel.Lanczos3, centreConvention);
+            if (xResidual < 1.0)
+                tile = tile.Reduceh(1.0 / xResidual, Enums.Kernel.Lanczos3, centreConvention);
+
+            // Perform enlargement
+            if (yResidual > 1.0 || xResidual > 1.0)
+            {
+                // Input displacement. For centre sampling, shift by 0.5 down
+                // and right.
+                double id = centreConvention ? 0.5 : 0.0;
 
-                // Perform enlargement
-                if (yResidual > 1.0 || xResidual > 1.0)
+                // Floating point affine transformation
+                using (Interpolate interpolate = Interpolate.NewFromName("bicubic"))
                 {
-                    // Floating point affine transformation
-                    using (Interpolate interpolate = Interpolate.NewFromName("bicubic"))
-                    {
-                        if (yResidual > 1.0 && xResidual > 1.0)
-                            tile = tile.Affine(new[] { xResidual, 0.0, 0.0, yResidual }, interpolate);
-                        else if (yResidual > 1.0)
-                            tile = tile.Affine(new[] { 1.0, 0.0, 0.0, yResidual }, interpolate);
-                        else if (xResidual > 1.0)
-                            tile = tile.Affine(new[] { xResidual, 0.0, 0.0, 1.0 }, interpolate);
-                    }
+                    if (yResidual > 1.0 && xResidual > 1.0)
+                        tile = tile.Affine(new[] {xResidual, 0.0, 0.0, yResidual}, interpolate, idx: id, idy: id,
+                            extend: Enums.Extend.Copy);
+                    else if (yResidual > 1.0)
+                        tile = tile.Affine(new[] {1.0, 0.0, 0.0, yResidual}, interpolate, idx: id, idy: id,
+                            extend: Enums.Extend.Copy);
+                    else if (xResidual > 1.0)
+                        tile = tile.Affine(new[] {xResidual, 0.0, 0.0, 1.0}, interpolate, idx: id, idy: id,
+                            extend: Enums.Extend.Copy);
                 }
             }
 

```
</details>
&nbsp;

Things that I've fixed (my second example code was wrong 😅):
- The integral box-shrink calulations were wrong (at least the final 200% should be done with `lanczos3`).
- The black border you saw was because the affine transform were filling new pixels with the `background` parameter (defaults to black). To fix this, I've set the extend parameter to `"copy"`, which takes each new pixel with the value of the nearest edge pixel.
- Some  redundant if-constructions were removed.

You may consider to use [`Resize`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_Resize_) (just like [my first example code](https://github.com/kleisauke/net-vips/issues/25#issuecomment-453271126)) for a more convenient way to resize images. This will save a lot of code. Are you sure that the output gives wrong results when the tiles are joined with centre convention?

I'll try to improve the performance (if I have some spare time left). GTiff2Tiles looks like a interesting university project. 👍

**Comment by Gigas002** [comment]
@kleisauke 

Thank you very much! I'll tell you the results as soon as I'll be able to test this code. About joining and wrong results: the joined tiles were OK, but the lowest tiles were cropped, so the error on that level were on the upper levels too.
By the way, is there any way to disable NetVips warnings in console? I tried [this](https://kleisauke.github.io/net-vips/tutorial/getting_started.html#logging-and-warnings) code sample, but it didn't worked out for me. I didn't find any samples about how to do it on other pages either.

**Comment by Gigas002** [comment]
@kleisauke

I managed to test this code, and yes, it seems, like the borders are now OK. 👍 Thank you again!

**Comment by kleisauke** [comment]
You can set the environment variable `VIPS_WARNING`, to suppress all warning messages from vips.  Or you can set the log handler of vips to an empty C# lambda expression, for example:
```csharp
var handlerId = Log.SetLogHandler("VIPS", Enums.LogLevelFlags.Warning, (domain, level, message) =>
{
    //Console.WriteLine("Domain: '{0}' Level: {1}", domain, level);
    //Console.WriteLine("Message: {0}", message);
});

// https://github.com/lovell/sharp/blob/master/test/fixtures/cielab-dagams.tiff
Image im = Image.NewFromFile("cielab-dagams.tiff");
Console.WriteLine(im);

Log.RemoveLogHandler("VIPS", handlerId);
````
In this example it will hide those `Incompatible type for "RichTIFFIPTC"; tag ignored` warnings. 

Code sample is fixed with https://github.com/kleisauke/net-vips/commit/388bc58fc77295b2f83c0d7fd69e8359dd94edc3, thanks!

**Comment by Gigas002** [comment]
@kleisauke Thanks, that code sample worked.

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.

**Comment by Gigas002** [comment]
Hello @kleisauke.
I fount out a little issue with shrink, don't know if it's an error or an expected behaviour by NetVips. I'm trying to shrink 4882x3832 pixels image to 1x1 pixel image. Using the code from your `temp.cs` (message above 04.02.19):

```c#
// Scaling calculations
double xFactor = (double) readXSize / writeXSize;
double yFactor = (double) readYSize / writeYSize;

// Calculate integral box shrink
// We will get the best quality (but be the slowest) if we let reduce
// do all the work. Leave it the final 200 - 300% to do as a compromise
// for efficiency.
int xShrink = Math.Max(1, (int) Math.Floor(1.0 / (xFactor * 2.0)));
int yShrink = Math.Max(1, (int) Math.Floor(1.0 / (yFactor * 2.0)));

// Calculate residual float affine transformation
double xResidual = xShrink / xFactor;
double yResidual = yShrink / yFactor;

//Try open input image and crop tile
NetVips.Image tileImage;
try
{
    tileImage = inputImage.Crop(readPosX, readPosY, readXSize, readYSize);
}
catch (Exception exception)
{
    throw new ImageException("Unable to create current tile.", exception);
}

// Fast, integral box-shrink
if (yShrink > 1)
{
    tileImage = tileImage.Shrinkv(yShrink);

    //Recalculate residual float.
    yResidual = (double) writeYSize / tileImage.Height;
}
if (xShrink > 1)
{
    tileImage = tileImage.Shrinkh(xShrink);

    //Recalculate residual float.
    xResidual = (double) writeXSize / tileImage.Width;
}

// Perform kernel-based reduction
if (yResidual < 1.0)
    tileImage = tileImage.Reducev(1.0 / yResidual, NetVips.Enums.Kernel.Lanczos3, centreConvention);
if (xResidual < 1.0)
    tileImage = tileImage.Reduceh(1.0 / xResidual, NetVips.Enums.Kernel.Lanczos3, centreConvention);
```

I've got the `yResidual` value equivalent `0.00026096033402922753` and got an `Exception` on string:
```c#
    tileImage = tileImage.Reducev(1.0 / yResidual, NetVips.Enums.Kernel.Lanczos3, centreConvention);
```

Here's the `Exception` text:
`NetVips.VipsException: 'unable to call reducev
TIFFSetField: D:\GTiff2Tiles\Temp\20190526151003730\Temp.tif: Unknown pseudo-tag 65538
reducev: reduce factor too large'`

**Comment by kleisauke** [comment]
Hi @Gigas002,

You could try to take a similar approach as [sharp](https://github.com/lovell/sharp) to ensure the length of the shortest edge never rounds below one pixel. See this commit: https://github.com/lovell/sharp/commit/7c631c0787915416e20a567a039516e99c81c42d.

**Comment by Gigas002** [comment]
Honestly, I didn't understand it. Here's some numbers for an example above that doesn't work:

`xFactor = 497`
`yFactor = 501.57142857142856`
`xShrink = 1`
`yShrink = 1`
`xResidual = 0.002012072434607646`
`yResidual = 0.0019937339789233839`
`tileImage.Width = 4473` (equals `readXSize` - **input** image's width)
`tileImage.Height = 3511` (equals `readYSize` - **input** image's height)
`1.0 / xResidual = 496.99999999999994`
`1.0 / yResidual = 501.5714285714285`
`writeXSize = 9` (**shrinked** image's width)
`writeYSize = 7` (**shrinked** image's height)

So, as you can see, shrinked image's sizes are more, than 1 pixel.

**Comment by kleisauke** [comment]
Hi @Gigas002,

Could you try this?:
<details>
 <summary>Resize.cs</summary>

```csharp
const int targetWidth = 9;
const int targetHeight = 7;
const bool centreConvention = false;

Image image = Image.NewFromFile("4473x3511.png", access: Enums.Access.Sequential);

// Scaling calculations
double hScale = 1.0 / ((double) image.Width / targetWidth);
double vScale = 1.0 / ((double) image.Height / targetHeight);

// Calculate integral box shrink
// We will get the best quality (but be the slowest) if we let reduce
// do all the work. Leave it the final 200 - 300% to do as a compromise
// for efficiency.
int hShrink = Math.Max(1, (int) Math.Floor(1.0 / (hScale * 2.0)));
int vShrink = Math.Max(1, (int) Math.Floor(1.0 / (vScale * 2.0)));

// Fast, integral box-shrink
if (vShrink > 1)
{
    image = image.Shrinkv(vShrink);

    vScale *= vShrink;
}

if (hShrink > 1)
{
    image = image.Shrinkh(hShrink);

    hScale *= hShrink;
}

// Any residual downsizing
if (vScale < 1.0)
    image = image.Reducev(1.0 / vScale, Enums.Kernel.Lanczos3, centreConvention);
if (hScale < 1.0)
    image = image.Reduceh(1.0 / hScale, Enums.Kernel.Lanczos3, centreConvention);

// Any upsizing
if (hScale > 1.0 || vScale > 1.0)
{
    // Input displacement. For centre sampling, shift by 0.5 down
    // and right.
    double id = centreConvention ? 0.5 : 0.0;

    // Floating point affine transformation
    using (Interpolate interpolate = Interpolate.NewFromName("bicubic"))
    {
        if (hScale > 1.0 && vScale > 1.0)
            image = image.Affine(new[] {hScale, 0.0, 0.0, vScale}, interpolate, idx: id, idy: id,
                extend: Enums.Extend.Copy);
        else if (hScale > 1.0)
            image = image.Affine(new[] {hScale, 0.0, 0.0, 1.0}, interpolate, idx: id, idy: id,
                extend: Enums.Extend.Copy);
        else
            image = image.Affine(new[] {1.0, 0.0, 0.0, vScale}, interpolate, idx: id, idy: id,
                extend: Enums.Extend.Copy);
    }
}

image.WriteToFile("9x7.png");
```
</details>

I tested `4882x3832 -> 1x1` and `4473x3511 -> 9x7` and it seems to work for me.

**Comment by Gigas002** [comment]
Thank you, that seems to work perfectly! :thumbsup:
